baseURL = "https://rsyncosx.netlify.app"
languageCode = "nb-NB"
title = "RsyncOSX"
theme = "hyde"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-111111111111-1"
canonifyURLs = true
copyright = "Thomas Evensen"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "RsyncOSX documentation."
  facebook = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-silver"
  featured_image = ""
  recent_posts_number = 3
  themeColor = "theme-base-08"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/rsyncOSX/RsyncOSX"},
  ]
